### ISSUE TITLE
Assert.Inconclusive test result want as ignored test case

### ISSUE THREAD

**Issue by PriyaSolanke286** [techtalk/SpecFlow.Plus.Examples#12]
Hi ,
I am using specRun with four profile for four environment(QC, TC, ET, PROD).
I want to ignore few test cases in ET environment.
I used Assert.Inconclusive to ignore test cases in ET environment and it is working.
Refer Following result

![image](https://user-images.githubusercontent.com/49298195/55936812-b68d7480-5c7a-11e9-8d3e-adbb94b2e17f.png)

I want the ignore test case by Assert.Inconclusive into ignored column.

Please give me some solution 
thanks

**Comment by SabotageAndi** [comment]
Please open a new issue in the main repo https://github.com/techtalk/SpecFlow
